name: Ubuntu

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Fetch dependencies
      run: go get -d ./...

    - name: Build
      run: go build

  nix-build:
    name: nix-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Nix
      run: curl https://nixos.org/nix/install | sh

    - name: Build
      run: sudo make nix # root required for Nix build sandbox
