name: Ubuntu

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Fetch dependencies
      run: go get -d ./...

    - name: Build
      run: go build
