name: Ubuntu

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Fetch dependencies
      run: go get -d ./...

    - name: Build
      run: go build

  nix-build:
    name: nix-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Nix
      run: |
        curl https://nixos.org/nix/install | sh
        . ~/.nix-profile/etc/profile.d/nix.sh
        nix-channel --update

    - name: Build
      run: |
        . ~/.nix-profile/etc/profile.d/nix.sh
        make nix

  live-iso:
    name: Live ISO
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Nix
      run: |
        curl https://nixos.org/nix/install | sh
        . ~/.nix-profile/etc/profile.d/nix.sh
        nix-channel --update

    - name: Generate Live ISO
      run: |
        . ~/.nix-profile/etc/profile.d/nix.sh
        make -C os live-iso
